### ISSUE TITLE
Add Application Configuration

### ISSUE THREAD

**Issue by KurtStam** [redhat-ipaas/ipaas-rest#10]
For things like:

- Running with or without back-end (in this case preload data from file)
- Configuration of the back-end endpoint access
- Authentication and Authorization Store
- Activate Session Recording (to collect data to run w/o backend)

**Comment by iocanel** [comment]
What do you have in mind for application configuration? 
I guess sicne we are using swarm and cdi, deltaspike may be the obvious choice. Thoughts?

**Comment by KurtStam** [comment]
Go for it :)

**Comment by jimmidyson** [comment]
Learning wildfly swarm slowly... How about https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/configuration/project_stages.html?

**Comment by iocanel** [comment]
Project stages looks good to me and it seems that it works with CDI too, so let's use that.

**Comment by jimmidyson** [comment]
Done now we've switched to spring boot.
