### ISSUE TITLE
CORS settings are breaking the use of the swagger-ui plugin

### ISSUE THREAD

**Issue by KurtStam** [redhat-ipaas/ipaas-rest#100]
javax.ws.rs.ForbiddenException: RESTEASY003700: Origin not allowed: chrome-extension://ljlmonadebogfjabhkppkoohjkjclfai

**Comment by jimmidyson** [comment]
When do you get this? It seems to work fine for me?

**Comment by KurtStam** [comment]
When running locally from runtime.

On Feb 16, 2017, at 17:02, Jimmi Dyson <notifications@github.com> wrote:

When do you get this? It seems to work fine for me?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/redhat-ipaas/ipaas-rest/issues/100#issuecomment-280476096>,
or mute the thread

**Comment by davsclaus** [comment]
Ah @KurtStam so you have installed a chrome browser plugin that has Swagger UI ?

**Comment by jimmidyson** [comment]
@davsclaus https://chrome.google.com/webstore/detail/swagger-ui-console/ljlmonadebogfjabhkppkoohjkjclfai

**Comment by jimmidyson** [comment]
This should be working now.
