### ISSUE TITLE
UI dependency alignment for RH Summit Demo milestone

### ISSUE THREAD

**Issue by mattrpav** [redhat-ipaas/ipaas-rest#123]
Need to align components and versions for the RH Summit Demo milestone b/w iPaaS and DM UI

**Comment by gashcrumb** [comment]
We should actually open this in ipaas-ui, here, lemme do that :-)

**Comment by gashcrumb** [comment]
Created https://github.com/redhat-ipaas/ipaas-ui/issues/188, let's close this one and discuss in the ipaas-ui issue.
