### ISSUE TITLE
launderThrowable usage is inconsistent

### ISSUE THREAD

**Issue by rhuss** [redhat-ipaas/ipaas-rest#137]
In [launderThrowable](https://github.com/rhuss/ipaas-rest/blob/adc756b7b4b0f2f94b3664592968af730c776ed3/rest/src/main/java/com/redhat/ipaas/rest/v1/controller/handler/exception/IPaasServerException.java#L49-L49) there is a return value in certain occassion, however it is sometimes [ignored]( https://github.com/rhuss/ipaas-rest/blob/381e3a761be5732813a1026ab42ac55d9b831376/rest/src/main/java/com/redhat/ipaas/rest/v1/dao/DataManager.java#L120-L120).

Also I would either always throw an exception with this method having a void return value or always return an exception which then needs to be rethrown. I would prefer first, as this is less dangerous to forget it (although the IDE will probably croak because of a missing throw in the catch clause.

**Comment by jimmidyson** [comment]
This is the same as used in [kubernetes-client](https://github.com/fabric8io/kubernetes-client/blob/592057e402c49b3b93e41f6219175a5931de6ee9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java#L55) that @iocanel came up with - I'm sure there's a good explanation for the return rather than throw.

**Comment by rhuss** [comment]
I discussed that with @iocanel at that time for kubernetes-client and afaik we agreed that its better to either always throw or always return. But could be wrong here.

**Comment by rhuss** [comment]
At least https://github.com/rhuss/ipaas-rest/blob/381e3a761be5732813a1026ab42ac55d9b831376/rest/src/main/java/com/redhat/ipaas/rest/v1/dao/DataManager.java#L120-L120 should be fixed then (by rethrowing the return value)
