### ISSUE TITLE
Create Integration test api for reseting the state during tests

### ISSUE THREAD

**Issue by jludvice** [redhat-ipaas/ipaas-rest#177]
There is need to reset backend state in 
* ipaas-ui/e2e tests (@jludvice working on e2e)
* ipaas-system-tests

The idea is to conditionally enable some MBean or jaxrs resource if we're in testing mode,
to allow set/reset test fixtures.

It was discussed on IRC with @chirino @rhuss and @iocanel 

Consideration 
* JMX Mbean / jax-rs with @ConditionalOnProperty 
* how to do auth / disable auth?
in case of JMX MBean/jolokia, it would be required to log into the openshift console first before accessing this test resource from e2e tests.

**Comment by jludvice** [comment]
QE could implement this test resource once we know which way to go.

**Comment by dsimansk** [comment]
@jludvice I think we can close this one as https://github.com/redhat-ipaas/ipaas-rest/pull/211 is merged already. 

Thanks @chirino!

**Comment by jludvice** [comment]
Agreed @dsimansk 

Thank you @chirino 

Closing issue
