### ISSUE TITLE
Remove TwitterMention and SalesforceUpsertContact connectors

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-rest#185]
We need to remove these connectors as they seem to confuse everyone that looks at the create connection wizard :-)

**Comment by gashcrumb** [comment]
![inkedscreencapture-localhost-4200-connections-create-connection-basics-1489669996182_li](https://cloud.githubusercontent.com/assets/351660/23997736/01ed4fe6-0a29-11e7-990c-c5dc52f93077.jpg)

**Comment by KurtStam** [comment]
They were already removed from the deployment.json last week..

**Comment by KurtStam** [comment]
Looks like this is a staging refresh issue.

**Comment by gashcrumb** [comment]
This looks all set, thanks!
