### ISSUE TITLE
Can we inline the connector in a connection

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-rest#196]
For example when I GET this connection by ID, I don't get the connector, just the connector ID:

https://ipaas-staging.b6ff.rh-idev.openshiftapps.com/api/v1/connections/2

Now that `configuredProperties` doesn't contain the whole form config, I need the connector object so I can get the form configuration for the connection detail page.  Don't think we need the actions inlined in the connector object in this case.

@KurtStam FYI

**Comment by KurtStam** [comment]
Sure - will load that up for you.

**Comment by gashcrumb** [comment]
@KurtStam thanks!  you're awesome :-)

**Comment by KurtStam** [comment]
https://github.com/redhat-ipaas/ipaas-rest/pull/198
