### ISSUE TITLE
twitter to salesforce example flow issues

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-rest#220]
1.  The 'Salesforce Example' endpoint step should be the last step, currently it's the second step
2.  `icon` attribute on the 'Twitter Example' and 'Salesforce Example' connections are unset in the integration

**Comment by gashcrumb** [comment]
@KurtStam FYI...

**Comment by gashcrumb** [comment]
Found another one, looks like the `action` object embedded in the steps for the salesforce/twitter connections don't have the `properties` fields set like in the `Timed Pull to Post Example`.

**Comment by gashcrumb** [comment]
Looks like we'll also need the `DataShape` property on this integration so I know what data type we can pass to the data mapper.

@chirino is that just a string property on the action with the Java class name?

**Comment by KurtStam** [comment]
@gashcrumb 
- I fixed the Steps and the Icon issues. 
- There are no twitter  or salesforce action config (only global/connection config) so that's why
- Can you explain DataShape a bit more? Maybe we should open a separate issue for this..

**Comment by gashcrumb** [comment]
@KurtStam yeah, let's open a new issue for the data shape thing...
