### ISSUE TITLE
Getting occasional 503

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-rest#222]
Seems to be two cases, one is when looking at connection details:

```
{
  "timestamp": 1490206753908,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.jboss.resteasy.spi.UnhandledException",
  "message": "java.lang.NullPointerException: position",
  "path": "\/api\/v1\/connections\/7"
}
```

But I also get a 503 occasionally when trying to fetch an individual integration, for example:

URL -> https://ipaas-staging.b6ff.rh-idev.openshiftapps.com/api/v1/integrations/1

```
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```

This was actually on the pre-flight OPTIONS methond, not even the subsequent GET.

**Comment by kahboom** [comment]
@jludvice and I are also getting this for most of the day. I can't even work locally as I'm using the staging API. @jimmidyson would say this is why we should be running the API locally lol but shhh...

**Comment by iocanel** [comment]
I am also hitting that issue all the time.

**Comment by KurtStam** [comment]
Is it because the token is expiring too soon? Do we have the full stack trace? Just wondering if it's auth related.

**Comment by gashcrumb** [comment]
I don't think it has anything to do with the token, as it can fail right
away after refreshing the browser etc.  Unfortunately no info really comes
back to the client beyond what I've reported.

**Comment by jludvice** [comment]
Hello @gashcrumb 

It might be unrelated, but @dsimansk mentioned some bug in openshift router.
"drop create" of applications/routes might cause "router panic" and weird issues in routing.
Is it possible that we're hitting this bug?

**Comment by gashcrumb** [comment]
@jludvice ooh, maybe, @iocanel @KurtStam WDYT?

**Comment by jludvice** [comment]
@dsimansk is this the bug you were talking about? 
https://bugzilla.redhat.com/show_bug.cgi?id=1371826

**Comment by iocanel** [comment]
Well, in my setup I don't edit nor delete routes, so I am not sure if this is related.

**Comment by gashcrumb** [comment]
K, things seem worse, it seems for `/api/v1/integrations` we now *always* get back:

```
{
  "timestamp": 1490380713212,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.jboss.resteasy.spi.UnhandledException",
  "message": "com.redhat.ipaas.core.IPaasServerException: An error has occurred.",
  "path": "\/api\/v1\/integrations"
}
```

**Comment by dsimansk** [comment]
@jludvice there's [newer issue](https://bugzilla.redhat.com/show_bug.cgi?id=1429823) against 3.4.1. It's probably not related to this issues, the effect of router panic consequently makes all routes->app unreachable permanently until router is restarted.

@jimmidyson do have enough permissions to access router pod logs or support ticket is needed?

**Comment by jimmidyson** [comment]
Any of us (as dedicated admins) should have access to router pod logs afaik.

**Comment by jimmidyson** [comment]
No looks like we can't view anything in default namespace... need to raise a ticket with openshift-provisioning@...

**Comment by jimmidyson** [comment]
This should now be fixed on staging by scaling down/up router pods (thanks ops!). Bug hit is apparently https://bugzilla.redhat.com/show_bug.cgi?id=1429823
