### ISSUE TITLE
Add data shape to connections/actions in example flow

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-rest#226]
Follow on from #220 we need this implemented in the example flow for the data mapper page -> https://github.com/redhat-ipaas/ipaas-rest/pull/188

**Comment by gashcrumb** [comment]
This is the config object we pass to the data mapper -> https://github.com/redhat-ipaas/datamapper-ui/blob/master/src/app/lib/ipaas-data-mapper/models/config.model.ts

looks like currently it just wants a string of the class name

**Comment by KurtStam** [comment]
@gashcrumb @chirino  I'm going to change dataShapeIn/Out to String and it will be populated with something like 
https://github.com/redhat-ipaas/connectors/blob/master/connectors/salesforce-upsert-contact-connector/src/main/resources/camel-connector.json#L16-L17

Sound ok?

**Comment by KurtStam** [comment]
https://github.com/redhat-ipaas/ipaas-rest/pull/230
