### ISSUE TITLE
Exception thrown during boot when using DockerHub image

### ISSUE THREAD

**Issue by dsimansk** [redhat-ipaas/ipaas-rest#237]
It seems that since release of `OpenJDK 1.8.0_121` image from DockerHub which is based on `fabric8/java-alpine-openjdk8-jdk/` there's an [exception thrown](https://gist.github.com/dsimansk/51f390d1e97b279deb347e9b04198017) during boot. I was able to reproduce it on Minishift and Dedicated env.

Googling around indicated that this may be caused by upgraded Java version. E.g. when I use f-m-p to build ipaas-rest with s2i binary (by default uses `fabric8/s2i-java` that is still on `_111`) the exception is gone.

**Comment by rhuss** [comment]
Thanks for the heads up, I will have a look.

**Comment by dsimansk** [comment]
Thanks @rhuss.

I forgot to mention that this exception leads to backend being unreachable as it inherently can't verify the access token.

**Comment by rhuss** [comment]
I see it now myself, too ;-) We are changing to a centos based image, too.

**Comment by dsimansk** [comment]
@rhuss have you found any specific OpenJDK bug for this? Maybe we should raise an issue to have it addressed properly for the future to prevent it from bitting us again:).

**Comment by rhuss** [comment]
@dsimansk unfortunately not ;-( I even doesn't know whether its maybe alpine specific as I now switched to another OS. But I can continue to look ...

BTW, the docker image is already bubbled up to dockerhub.
