### ISSUE TITLE
Attribute to store datamapper output on Integration

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-rest#240]
Or maybe it should be part of the Step perhaps, like a attribute to reference n files maybe?

@chirino @jimmidyson FYI

**Comment by gashcrumb** [comment]
So this is what the data mapper produces -> https://github.com/redhat-ipaas/datamapper-ui/blob/master/src/app/lib/ipaas-data-mapper/models/mapping.definition.model.ts

**Comment by gashcrumb** [comment]
Ah, is it then in just in `configuredProperties` as `atlasMapping` then?  I could go along with that...

**Comment by gashcrumb** [comment]
The `atlassmapping` property currently stored in the `Twitter to Salesforce Example` integration is kinda totally different from that typescript interface :-/

**Comment by KurtStam** [comment]
@gashcrumb I think it needs to go in the altlasmapping field on the data mapper. 

@mattrpav @chirino maybe you can shine a light on this? We are currently using the JSON mentioned in:
https://github.com/redhat-ipaas/ipaas-datamapper/issues/7

**Comment by KurtStam** [comment]
@gashcrumb the data mapper service on staging has been updated to contain the twitter and Salesforce classes, and I've updated the atlas mapping in the deployment.json for the data mapper to reflect the use of these classes. So it should be good to go now!
