### ISSUE TITLE
data mapper can't find Java types

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-rest#242]
Have the data mapper hooked into the UI a bit better, so we get the types out of the flow.  But it can't find the referenced Java types:

```
{
  "JavaClass": {
    "jsonType": "com.mediadriver.atlas.java.v2.JavaClass",
    "status": "NOT_FOUND",
    "javaEnumFields": {
      "javaEnumField": [
        
      ]
    },
    "javaFields": {
      "javaField": [
        
      ]
    },
    "fullyQualifiedName": "org.foo.salesforce.upsert.contact.Contact"
  }
}
```

Well, maybe it's just that class name in the example :-)  The twitter one fails too, I guess it doesn't yet have access to the project classpath yet?

**Comment by KurtStam** [comment]
You want to treat this field as a JSON Blob and not parse it, which is why I had escaped the quotes in it. The Rest layer doesn't have these types either and we will pass it straight on to the DataMapper.  @gashcrumb does that makes sense? It could very well be that I don't understand how this is supposed to work!

**Comment by KurtStam** [comment]
I guess this is sort of the same question as https://github.com/redhat-ipaas/ipaas-rest/issues/240 
@mattrpav @chirino can you comment?

**Comment by mattrpav** [comment]
Are you launching the service using the atlas.itests project? If so, the jars are probably not in the classpath with the atlas.itests project.  These classes should be:

 * http://localhost:8585/v2/atlas/java/class?className=twitter4j.User
 * http://localhost:8585/v2/atlas/java/class?className=org.apache.camel.salesforce.dto.Contact

**Comment by KurtStam** [comment]
@mattrpav we are talking about the config that the UI layer creates as part of the mapping. So that JSON should not reference Java?

**Comment by mattrpav** [comment]
The JSON being returned is the design time list of available fields for mapping to a Java class SFDC.Contact. If this was XML, it'd look different.

**Comment by KurtStam** [comment]
Moving this issue to the data mapper ui-services project: https://github.com/redhat-ipaas/ipaas-datamapper/issues/20
