### ISSUE TITLE
Dashboard-Specific API Requirements

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-rest#246]
One of the sprint 10 requirements is the dashboard, for which we have issues [here](https://github.com/redhat-ipaas/ipaas-ui/issues/296) and [here](https://github.com/redhat-ipaas/ipaas-ui/issues/300). While some of the filtering can be done from the UI, it's preferable that this come from the backend.

We need:
1. A `lastUpdated` date on Integrations.
2. A `timesUsed` or similar property that displays how often an integration has been used, distinguishing which are more "popular" than others. (I believe this is "messages exchanged" or "message history" in Camel? I'm a newbie so taking some stabs in the dark here.)
3. A `status` for Integrations.
4. A `limit` on the number of integrations and connections we can pull from the API so we won't  load all unnecessarily.

Hopefully I didn't miss anything. Here is the design with what we need, for reference:

![225246460](https://cloud.githubusercontent.com/assets/3844502/24411332/9ca6deb6-13a3-11e7-86b4-0c232ee3fb9f.png)

![225246638](https://cloud.githubusercontent.com/assets/3844502/24411337/9f5674aa-13a3-11e7-85e1-8211871242bb.png)

cc @KurtStam

**Comment by KurtStam** [comment]
1. Added the lastUpdated field with type Date. The field gets set on POST and PUT of an Integration.
2. Added timesUsed as Big Integer. For now it makes up an increasing integer.
3. There already exists a currentStatus field that you can use.
4. To set a limit=n, you can add query parameters page=1&per_page=n

![screen shot 2017-03-28 at 4 48 27 pm](https://cloud.githubusercontent.com/assets/35576/24426986/6a5a5936-13d7-11e7-83b3-8929c03e7ebb.png)
