### ISSUE TITLE
Getting back HTTP 500 when doing a PUT to update integration desiredStatus

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-rest#266]
Doing a PUT with the integration object to:

https://ipaas-staging.b6ff.rh-idev.openshiftapps.com/api/v1/integrations/3

in this case I want to set `desiredStatus` to `Activated`.

**Comment by gashcrumb** [comment]
Error message:
```
{timestamp: 1490904216076, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.jboss.resteasy.spi.UnhandledException"
message
:
"javax.persistence.EntityNotFoundException: Can not find integration with id 3"
path
:
"/api/v1/integrations/3"
status
:
500
timestamp
:
1490904216076
Name

```

**Comment by KurtStam** [comment]
@gashcrumb  Well that sucks, I'm assuming you got the integration from GET on /api/v1/integrations/3? So you know it's there?

**Comment by gashcrumb** [comment]
well, it's not there now, I managed to delete it via the UI so that's interesting...

**Comment by KurtStam** [comment]
I refreshed the DB, the example data only has 2 integrations. so the next one you create would be 3.

**Comment by gashcrumb** [comment]
Yeah, seems to maybe be a sporadic thing, maybe it's an openshift problem?

**Comment by KurtStam** [comment]
OK leaving this open for now then. Please let us know if it happens again.

**Comment by KurtStam** [comment]
Closing as it hasn't happened since.
