### ISSUE TITLE
Pull out the 'kind' from the dataType field for data shape

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-rest#274]
Since we bake the` kind` into the dataType field (like `'java:foo.blah.Myclass'`) now I have to have special parsing client-side.  Why not have the `kind` in a separate field?

**Comment by gashcrumb** [comment]
Another option is just align to the URL scheme that the data mapper uses in it's mapping file maybe, though the inputs for the component are just the class names for Java.

**Comment by KurtStam** [comment]
@gashcrumb The metadata in Camel have it as one field. I like consistency :). I can break it apart if you really want. If so 'none' and '*' would go in the kind field I think.

**Comment by gashcrumb** [comment]
hmm, I don't know.  I guess maybe we'll have to revisit this when we deal with `json` and other non-java cases.  I definitely think *not* passing along a URI-like syntax would be better in general,

**Comment by jimmidyson** [comment]
I much prefer the separate field approach that @gashcrumb proposes. The `kind` can be the distinguishing field to parse to specific types as needed. Much easier to work with IMO.

**Comment by KurtStam** [comment]
@gashcrumb PR is ready for merge
