### ISSUE TITLE
Rollout failing

### ISSUE THREAD

**Issue by jimmidyson** [redhat-ipaas/ipaas-rest#284]
See https://jenkins-ipaas-ci.b6ff.rh-idev.openshiftapps.com/job/ipaas-rest-rollout/260/console

**Comment by iocanel** [comment]
It seems that its a failure to build the image:

    [INFO] 
    [INFO] --- fabric8-maven-plugin:3.3.0:build (default-cli) @ runtime ---
    [INFO] F8: Using OpenShift build with strategy S2I
    [INFO] F8: Running generator spring-boot
    [INFO] F8: spring-boot: Using Docker image fabric8/s2i-java:2.0 as base / builder
    [INFO] Copying files to /home/jenkins/workspace/ipaas-rest-rollout/runtime/target/docker/rhipaas/ipaas-
    rest/latest/build/maven
    [INFO] Building tar: /home/jenkins/workspace/ipaas-rest-rollout/runtime/target/docker/rhipaas/ipaas-
    rest/latest/tmp/docker-build.tar
    [INFO] F8: [rhipaas/ipaas-rest:latest] "spring-boot": Created docker source tar 
    /home/jenkins/workspace/ipaas-rest-rollout/runtime/target/docker/rhipaas/ipaas-rest/latest/tmp/docker-
    build.tar
    [INFO] F8: Using BuildServiceConfig ipaas-rest-s2i for Source strategy
    [INFO] F8: Adding to ImageStream ipaas-rest
    [INFO] F8: Starting Build ipaas-rest-s2i
    $ [ERROR] F8: Failed to execute the build
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:

And then we see:


    [ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.3.0:build (default-cli) on project 
    runtime: Failed to execute the build: Unable to build the image using the Openshift build service: An error 
    has occurred. timeout: Socket closed -> [Help 1]

@rhuss: Do you have any idea?

**Comment by rhuss** [comment]
@iocanel  Sorry for the error message, need to update this, now that we have the lates okhttp in kubernetes client. There's a jira ticket open for this.

The issue is that the S2I build fails and your best bet is to check the OpenShift build object and build pod.

**Comment by jimmidyson** [comment]
Unfortunately the build pod is no more as the project is cleaned up I think (@iocanel?). Can't the build pod log be output somehow?

**Comment by iocanel** [comment]
In arquillian-cube-kubernetes we recently introduced the notion of FeedbackProvider which is a mechanism for providing feedback to the user when things go wrong. For example when the installre resources don't get ready in time, the feedback provider finds the related pods, and displays logs and events.

I am wondering if f-m-p could optionally do something similar, and display the `build pod log` when the build fails. 

Makes any sense?

**Comment by jimmidyson** [comment]
Looks like there was an old failed s2i that had hung... Killed them all and now things are running through.

**Comment by rhuss** [comment]
@iocanel yes, would be  a good idea to provide more information from the various objects if things go havoc. Will need to fix the 'streamed closed' problem first, hopefully openshift presents  a meaningful error message, too.

**Comment by jimmidyson** [comment]
Failing with different error now... https://jenkins-ipaas-ci.b6ff.rh-idev.openshiftapps.com/job/ipaas-rest-rollout/261/console

**Comment by jimmidyson** [comment]
BTW i think the stream closed issue was because the buildb pod didn't actually start. Build policy is serial by default so if one build is running, subsequent builds start in New state. Probably need to wait for build to start with some timeout and cleanup logic before trying to get logs from build.

**Comment by iocanel** [comment]
@jimmidyson: can we close this one?

**Comment by jimmidyson** [comment]
Yeah I think so.
