### ISSUE TITLE
Return `created` for Integrations

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-rest#302]
We already receive `lastUpdated` for Integrations, which is great and is currently used in the Dashboard. It looks strange when an Integration has not been updated, as that entire column remains blank. Please add `created` as a property that is included as part of the Integration object.

An example of where we would use both the `created` and `lastUpdated` properties for an Integration (this is the Dashboard):

<img width="552" alt="screenshot 2017-04-13 10 31 13" src="https://cloud.githubusercontent.com/assets/3844502/25010634/baae31f6-2038-11e7-9623-5c2088a64f17.png">

**Comment by KurtStam** [comment]
@kahboom I've added CreatedDate and LastUpdated on Connection and Integration.

**Comment by kahboom** [comment]
Ty @KurtStam !
