### ISSUE TITLE
IntegrationController event cycle

### ISSUE THREAD

**Issue by rhuss** [redhat-ipaas/ipaas-rest#312]
When an exception occurs while enqueue() in IntegrationHandler, the Integration object is updated, which causes another changed-event to be enqueue(), where the same exception occurs, ... and so on.

--> https://github.com/redhat-ipaas/ipaas-rest/blob/32c2d7fad1bd9092f61aad5b395d69df201a9889/controllers/src/main/java/com/redhat/ipaas/controllers/IntegrationController.java#L148-L157

**Comment by chirino** [comment]
Think you resolved this one right @rhuss ?

**Comment by rhuss** [comment]
Yes, this is resolved.
