### ISSUE TITLE
Integration "changed-event" thrown twice on create

### ISSUE THREAD

**Issue by rhuss** [redhat-ipaas/ipaas-rest#313]
1. https://github.com/rhuss/ipaas-rest/blob/3cfa64cfdad203fe347158e727a16ce578dfe338/dao/src/main/java/com/redhat/ipaas/dao/manager/DataManager.java#L191-L191

2. https://github.com/rhuss/ipaas-rest/blame/c5b788abb7b2fc53514717bb3c61eae1192a7ffb/rest/src/main/java/com/redhat/ipaas/rest/v1/handler/integration/IntegrationHandler.java#L120-L120

The second call contains also the `Integration` object without id (so it not very helpful anyway). @iocanel  do you remember why the event is thrown a second time ?

**Comment by chirino** [comment]
event bus is no longer used in the IntegrationHander
