### ISSUE TITLE
Need more sample integrations in various states

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-rest#318]
@KurtStam to implement this view it'd be great to have a few more integrations that are fixed in these various states just so the view can be further developed:

![d4e20a08-1560-11e7-9b14-490f46a96169](https://cloud.githubusercontent.com/assets/351660/25183095/94ca397a-24e4-11e7-970b-4b4fb91c6342.jpg)

It doesn't really work to create the integrations from the UI and hope that they work or don't work, and anyways all the integrations disappear eventually.

@kahboom FYI

**Comment by kahboom** [comment]
+1 This would be awesome.. some 'In Progress', some failed, some passed, some drafts, some inactive, etc. FYI the green checkmark means that there is no `statusMessage`, which would mean it has passed, however, the integration can still be a Draft or just Inactive, for example.

**Comment by KurtStam** [comment]
@gashcrumb @kahboom Please review the PR to see if this has all the state combos you need.
