### ISSUE TITLE
Generated function.yaml configures endpoint parameters that are secrets

### ISSUE THREAD

**Issue by chirino** [redhat-ipaas/ipaas-rest#322]
Example:

uri: twitter-mention:?accessToken=&accessTokenSecret=&consumerKey=&consumerSecret=

Shouldn't stuff like consumerSecret come in via application.properties via secrets?

**Comment by iocanel** [comment]
Any connector property that has the secret flag set to true, may be present in uri using a placeholder, that picks up value from `/opt/integration/secrets.properties`.  

If the actual value is present in the uri, then its a bug.

@chirino: from the description its not clear to me what exactly is the problem.

**Comment by davsclaus** [comment]
No those should be configure from spring-boot, eg like in that application.properties file

**Comment by davsclaus** [comment]
The camel uri should just be `twitter-mention` just like the example
https://github.com/redhat-ipaas/connectors/blob/master/examples/twitter-salesforce-example/src/main/java/com/redhat/ipaas/example/MentionAddContractRoute.java#L26

**Comment by davsclaus** [comment]
Whatever magic @iocanel then has to load that `/opt/integration/secrets.properties` file and make those as spring boot auto configuration is beyond my scope/knowledge. All Camel care about is that its configured using spring boot auto configuration, eg 

https://github.com/redhat-ipaas/connectors/blob/master/connectors/twitter-mention-connector/src/main/java/com/redhat/ipaas/connector/twitter/springboot/TwitterMentionConnectorConfiguration.java

https://github.com/redhat-ipaas/connectors/blob/master/connectors/twitter-mention-connector/src/main/java/com/redhat/ipaas/connector/twitter/springboot/TwitterMentionConnectorAutoConfiguration.java

**Comment by chirino** [comment]
Fixed now
