### ISSUE TITLE
If there's no errors in an integration, don't set statusMessage

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-rest#323]
Right now in the UI the presence of `statusMessage` in the integration object is treated as an error and a red x is shown.  If the attribute isn't in the integration a green check is shown.

If there's no errors to report for an integration then `statusMessage` shouldn't be set, sounds like in some case it's set to 'Activated' for a successful case.

**Comment by kahboom** [comment]
This is higher priority than adding an "Error" state, as it's a bit of a workaround in the meantime.

**Comment by gashcrumb** [comment]
So one example, I create an integration, it goes to 'Pending' and then `statusMessage` is also set to `pending`, I think it should be null unless there's a reason for it to be otherwise...

**Comment by gashcrumb** [comment]
I mean, I guess I could put in a quick hack to hide the red x if `statusMessage === currentStatus`

**Comment by rhuss** [comment]
I can send a quick fix asap ... standby

**Comment by gashcrumb** [comment]
@rhuss awesome, thanks!

**Comment by rhuss** [comment]
https://github.com/redhat-ipaas/ipaas-rest/pull/324 is the PR which should fix this
