### ISSUE TITLE
GitHub WebHook is garbled

### ISSUE THREAD

**Issue by zregvart** [redhat-ipaas/ipaas-rest#346]
This is what I get as a WebHook's payload URL:

    null/namespaces/myproject/buildconfigs/thingamajig/webhooks/84010aa8-c27d-4c53-a10d-1c03c89bae57/github

- the scheme/hostname is missing
- namespace should be `ipaas` not `myproject`

**Comment by chirino** [comment]
Yep, I ran into this too:

<img width="1030" alt="webhooks" src="https://cloud.githubusercontent.com/assets/103255/25459858/64b9d2ac-2aae-11e7-9973-3b4ac047fc84.png">

**Comment by jimmidyson** [comment]
This should be set in `application.properties` in ipaas-rest configmap as key `openshift.openshiftApiBaseUrl`. Can you check if that is set properly in your configmap and mounted correctly in your pod?

**Comment by jimmidyson** [comment]
Looks like this was garbled in 922409253c5ad4dac578ddea7084b486f2574658. Fixing up.

**Comment by chirino** [comment]
Tested out the new commit. Now seeing this:

<img width="1022" alt="webhooks" src="https://cloud.githubusercontent.com/assets/103255/25490620/5fd34164-2b3b-11e7-936e-52e8499b9680.png">

which does not seem right either.  The project namespace is ipaas, and my domain name is ipaas.192.168.64.2.xip.io

**Comment by jimmidyson** [comment]
Can you share your ipaas-rest-config configmap?

**Comment by chirino** [comment]
sure..

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ipaas-rest-config
  namespace: ipaas
  selfLink: /api/v1/namespaces/ipaas/configmaps/ipaas-rest-config
  uid: 33c0f664-2b59-11e7-9e20-5618f11011fc
  resourceVersion: '1153'
  creationTimestamp: '2017-04-27T14:52:57Z'
  labels:
    app: redhat-ipaas
    component: ipaas-rest
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
data:
  application.yml: |-
    deployment:
      file: com/redhat/ipaas/dao/deployment.json
    resteasy:
      jaxrs:
        app:
          registration: property
          classes: com.redhat.ipaas.rest.v1.V1Application
    cors:
      allowedOrigins: http://localhost:4200, https://ipaas.192.168.64.2.xip.io

    cache:
      cluster:
        name: IPaaSCluster
      max:
        entries: 100
    spring:
      zipkin:
        enabled: false
      datasource:
        url: jdbc:postgresql://ipaas-db:5432/ipaas?sslmode=disable
        username: ipaas
        password: W5H7fvVOr3TAdhCa
        driver-class-name: org.postgresql.Driver
    security:
      basic:
        enabled: false
    management:
      port: 8181
      security:
        enabled: true
    endpoints:
      health:
        sensitive: false
      jsondb:
        enabled: true
    github:
      service: ipaas-github-proxy.${NAMESPACE}.svc
    openshift:
      openShiftHost: ipaas-openshift-proxy.${NAMESPACE}.svc
    keycloak:
      enabled: true
      configurationFile: file:config/ipaas-client.json
    dao:
      kind: jsondb
  ipaas-client.json: |-
    {
      "realm": "ipaas",
      "bearer-only": true,
      "auth-server-url": "https://ipaas.192.168.64.2.xip.io/auth",
      "ssl-required": "external",
      "resource": "ipaas-rest",
      "allow-any-hostname" : false
    }

```

**Comment by iocanel** [comment]
@jimmidyson, @chirino: It seems that the openshift templates are not up to date with ipaas-rest and we need to add:

    private String apiBaseUrl;

    private String namespace;

So @jimmidyson I am calling dibs on it :-P

**Comment by iocanel** [comment]
Ohhhh man!

**Comment by iocanel** [comment]
I think that now we can close.
