### ISSUE TITLE
Generated integrations do not expose the Jolokia port

### ISSUE THREAD

**Issue by chirino** [redhat-ipaas/ipaas-rest#352]
![image](https://cloud.githubusercontent.com/assets/103255/25459404/0e6ff9d2-2aac-11e7-94db-5b6597c264b9.png)

We should expose the Jolokia port so that developers and inspect the JVM in greater detail.

**Comment by jimmidyson** [comment]
What do you mean by expose? The port is listening and listed in pods ports. What more do you need? Any ideas @rhuss?

**Comment by dsimansk** [comment]
Afaik, port name has to be set to`jolokia` for the OpenShift Java Console to pick it up.

**Comment by jimmidyson** [comment]
Really? I thought it was either name or number, not just name, but perhaps that's changed. It's f-m-p generating that so would require a change there iirc. Let's wait for @rhuss.

**Comment by rhuss** [comment]
@jimmidyson @dsimansk Actually, I _think_ it works with a port only (without name), but the best answer is to try it out. @chirino in your screenshot  you _do_ expose the 8778 port (which is jolokia's port). But I think it wouldn't harm to add a `name: jolokia`

**Comment by jimmidyson** [comment]
Looks like f-m-p should enrich that port name - https://github.com/fabric8io/fabric8-maven-plugin/blob/ef580fa8173e198931624114ecdc62d6b1e1248d/enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/PortNameEnricher.java#L42

**Comment by jimmidyson** [comment]
Ah yes we're not using f-m-p here are we... let me take a quick look, should be simple fix.

**Comment by chirino** [comment]
Should we also expose the SB health check ports while we are at it?

**Comment by jimmidyson** [comment]
@chirino You don't have to expose those ports at all unless something actually needs to discover them. The ports are still accessible in the pod, whether they're declared in the manifest or not so I would say no for now, but keep it in mind for future integration with other systems if needed.

**Comment by chirino** [comment]
So the integration's DC's should be configured with heath/readiness checks then?

**Comment by jimmidyson** [comment]
Readiness checks can use non-published ports but yes we should be adding readiness, liveness probes to deployments templates.
