### ISSUE TITLE
Save Integration

### ISSUE THREAD

**Issue by KurtStam** [redhat-ipaas/ipaas-rest#76]
Implement REST API to Save an Integration

https://issues.jboss.org/browse/IPAAS-173

**Comment by gashcrumb** [comment]
Yeah, for this we need to add `steps`, current interface that I see in swagger is:

```
Integration {
tags (Array[Tag], optional),
userId (string, optional),
configuration (string, optional),
integrationTemplateId (string, optional),
users (Array[User], optional),
integrationTemplate (IntegrationTemplate, optional),
id (string, optional),
name (string, optional)
}
```

Might as well make `steps` an array of `Connection` for now I guess.

**Comment by KurtStam** [comment]
I've add a Collection of Steps as well as Connection. Note that this was not part of the initial model:
https://cloud.githubusercontent.com/assets/3844502/22932276/4f045a46-f295-11e6-868e-216006329cd8.png where the relation goes through the IntegrationTemplate. We should review this in the next sprint.

**Comment by gashcrumb** [comment]
You're absolutely right, I wonder if we should really be saving an IntegrationTemplate + an Integration that references the template.  @jimmidyson thoughts?

Definitely something we need to start defining like now.  Or yesterday :-)

**Comment by jimmidyson** [comment]
Integration templates are blueprints that are used to create new integrations from. There should be no relation to integration template once an integration is created from one.

**Comment by gashcrumb** [comment]
Ah, okay great.  Should probably then update the model and any related diagrams then to remove that relationship if there is one.  Definitely makes it easier from the frontend's perspective too, I was starting to worry we'd have to coordinate that :-)

**Comment by jimmidyson** [comment]
I'll review the model tomorrow or early next week. There's probably a reasonable amount of change in there - I wasn't really aware of that diagram until now tbh.

**Comment by KurtStam** [comment]
@jimmidyson that was model was where we created the java model from.

**Comment by jimmidyson** [comment]
OK that was before I did anything on the project though. We need to look at it again to see if it makes sense now with all the changes we've had to incorporate into flow and definitions.
