### ISSUE TITLE
Hook keycloak up to OpenShift as OAuth provider

### ISSUE THREAD

**Issue by KurtStam** [redhat-ipaas/ipaas-rest#79]
ATM keycloak is deployed as a standalone server which handles both authentication via keycloak form as well as with a token. We'd like to hook OpenShift up as the OAuth provider for keycloak, so the token becomes the OpenShift token. In keycloak we can then define the roles we need for the iPaaS application, while Openshift still manages the access roles for what openshift resources this type of user is allowed have access to. For now all users are of type/role 'citizen developer'.

We probably need some code how to discover (or configuration) the OpenShift server we want to connect to.

https://issues.jboss.org/browse/IPAAS-149
https://issues.jboss.org/browse/IPAAS-180
https://issues.jboss.org/browse/IPAAS-181

It probably would be good to be able to run w/o OpenShift as OAuth provider in development. 

Some resources:

- https://docs.openshift.com/enterprise/3.0/architecture/additional_concepts/authentication.html#oauth
- Obtain openshift token using: `<master>/oauth/token`
- https://github.com/redhat-ipaas/ipaas-rest/issues/11

**Comment by jimmidyson** [comment]
Done.
