### ISSUE TITLE
Use a single style of maven properties

### ISSUE THREAD

**Issue by iocanel** [redhat-ipaas/ipaas-rest#82]
So is it....

version.xxx or xxx.version ?
xxx-yyy-version or xxx.yyy.version?
xxx-yyy.version or xxx.yyy.version?

and of course

xxx-maven-plugin.version or maven-xxx-plugin.version?

Personally, I don't care what it is as long as its a single style.

**Comment by jimmidyson** [comment]
+1. Personally xxx-yyy.version and xxx-yyy-maven-plugin.version

**Comment by iocanel** [comment]
xxx-yyy.version and xxx-yyy-maven-plugin.version it will be then

**Comment by iocanel** [comment]
In other words <artfiactId>.version

**Comment by jimmidyson** [comment]
Fixed by #84
