### ISSUE TITLE
Add persistence to our model

### ISSUE THREAD

**Issue by KurtStam** [redhat-ipaas/ipaas-rest#89]
We've been talking about adding persistence to our model, using postgresql and an ORM layer. Turns out this doesn't map very well to Immutable objects 

> "It's seems that hibernate design (with unit of work pattern and various features like lazy loading) 
> do not play well with idea of immutable objects. We had much better results by integrating
> with query/result mappers like JDBI, unfortunately it is not included in 2.0 (https://github.com/immutables/immutables/issues/97).
> Also there's MongoDB integration (http://immutables.github.io/mongo.html) as another example of query/result mapper (rather than ORM)
> I have doubts that dedicated Hibernate/JPA support will make any sense due to the nature of ORM."

So I think we have 2 options:

- try using something like Mongo, for which they do have support (yuck).
- creating a second model that can be used for the persistence, and then handing it over to the Immutable model (yuck).

Thoughts?

**Comment by chirino** [comment]
So we have persistence now via the JsonDB.  I know we are going to continue to evolve it to be more SQL based, but I think we can close this issue now
